/**
 * Server-side invoice label translations for Swiss-compliant invoices.
 * Covers all 5 SRAtix widget languages.
 */

export type InvoiceLang = 'en' | 'fr' | 'de' | 'it' | 'zh-TW';

export interface InvoiceLabels {
  invoice: string;
  invoiceNumber: string;
  date: string;
  from: string;
  billTo: string;
  vatId: string;
  uid: string;
  order: string;
  event: string;
  eventDate: string;
  venue: string;
  description: string;
  qty: string;
  unitPrice: string;
  total: string;
  subtotal: string;
  discount: string;
  grandTotal: string;
  paidOn: string;
  paymentStatus: string;
  paid: string;
  currency: string;
  iban: string;
  /** QR-bill section header */
  paymentSection: string;
  creditor: string;
  debtor: string;
  reference: string;
  /** Footer */
  generatedBy: string;
}

const labels: Record<InvoiceLang, InvoiceLabels> = {
  en: {
    invoice: 'Invoice',
    invoiceNumber: 'Invoice No.',
    date: 'Date',
    from: 'From',
    billTo: 'Bill To',
    vatId: 'VAT',
    uid: 'UID',
    order: 'Order',
    event: 'Event',
    eventDate: 'Date',
    venue: 'Venue',
    description: 'Description',
    qty: 'Qty',
    unitPrice: 'Unit Price',
    total: 'Total',
    subtotal: 'Subtotal',
    discount: 'Discount',
    grandTotal: 'Total',
    paidOn: 'Paid on',
    paymentStatus: 'Payment status',
    paid: 'Paid',
    currency: 'Currency',
    iban: 'IBAN',
    paymentSection: 'Payment receipt',
    creditor: 'Creditor',
    debtor: 'Debtor',
    reference: 'Reference',
    generatedBy: 'Generated by SRAtix',
  },
  fr: {
    invoice: 'Facture',
    invoiceNumber: 'N° de facture',
    date: 'Date',
    from: 'De',
    billTo: 'Facturer à',
    vatId: 'TVA',
    uid: 'IDE',
    order: 'Commande',
    event: 'Événement',
    eventDate: 'Date',
    venue: 'Lieu',
    description: 'Description',
    qty: 'Qté',
    unitPrice: 'Prix unitaire',
    total: 'Total',
    subtotal: 'Sous-total',
    discount: 'Remise',
    grandTotal: 'Total',
    paidOn: 'Payé le',
    paymentStatus: 'Statut du paiement',
    paid: 'Payé',
    currency: 'Devise',
    iban: 'IBAN',
    paymentSection: 'Récépissé de paiement',
    creditor: 'Créancier',
    debtor: 'Débiteur',
    reference: 'Référence',
    generatedBy: 'Généré par SRAtix',
  },
  de: {
    invoice: 'Rechnung',
    invoiceNumber: 'Rechnungs-Nr.',
    date: 'Datum',
    from: 'Von',
    billTo: 'Rechnung an',
    vatId: 'MwSt.',
    uid: 'UID',
    order: 'Bestellung',
    event: 'Veranstaltung',
    eventDate: 'Datum',
    venue: 'Veranstaltungsort',
    description: 'Beschreibung',
    qty: 'Menge',
    unitPrice: 'Einzelpreis',
    total: 'Total',
    subtotal: 'Zwischensumme',
    discount: 'Rabatt',
    grandTotal: 'Gesamtbetrag',
    paidOn: 'Bezahlt am',
    paymentStatus: 'Zahlungsstatus',
    paid: 'Bezahlt',
    currency: 'Währung',
    iban: 'IBAN',
    paymentSection: 'Zahlungsbeleg',
    creditor: 'Zahlungsempfänger',
    debtor: 'Zahlungspflichtiger',
    reference: 'Referenz',
    generatedBy: 'Erstellt mit SRAtix',
  },
  it: {
    invoice: 'Fattura',
    invoiceNumber: 'N. fattura',
    date: 'Data',
    from: 'Da',
    billTo: 'Fatturare a',
    vatId: 'IVA',
    uid: 'IDI',
    order: 'Ordine',
    event: 'Evento',
    eventDate: 'Data',
    venue: 'Sede',
    description: 'Descrizione',
    qty: 'Qtà',
    unitPrice: 'Prezzo unitario',
    total: 'Totale',
    subtotal: 'Subtotale',
    discount: 'Sconto',
    grandTotal: 'Totale',
    paidOn: 'Pagato il',
    paymentStatus: 'Stato del pagamento',
    paid: 'Pagato',
    currency: 'Valuta',
    iban: 'IBAN',
    paymentSection: 'Ricevuta di pagamento',
    creditor: 'Creditore',
    debtor: 'Debitore',
    reference: 'Riferimento',
    generatedBy: 'Generato da SRAtix',
  },
  'zh-TW': {
    invoice: '發票',
    invoiceNumber: '發票編號',
    date: '日期',
    from: '開票方',
    billTo: '帳單寄至',
    vatId: '稅號',
    uid: 'UID',
    order: '訂單',
    event: '活動',
    eventDate: '日期',
    venue: '場地',
    description: '說明',
    qty: '數量',
    unitPrice: '單價',
    total: '合計',
    subtotal: '小計',
    discount: '折扣',
    grandTotal: '總計',
    paidOn: '付款日期',
    paymentStatus: '付款狀態',
    paid: '已付款',
    currency: '貨幣',
    iban: 'IBAN',
    paymentSection: '付款收據',
    creditor: '收款方',
    debtor: '付款方',
    reference: '參考編號',
    generatedBy: '由 SRAtix 產生',
  },
};

export function getInvoiceLabels(lang: string): InvoiceLabels {
  const key = lang as InvoiceLang;
  return labels[key] || labels.en;
}
